civi_upgrade_manager_upgrade_report:
    resource: "@CiviUpgradeManagerBundle/Controller/UpgradeReportController.php"
    type:     annotation

civi_upgrade_manager:
    resource: "@CiviUpgradeManagerBundle/Resources/config/routing.yml"
    #type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
