
check:
    path:     /check
    defaults: { _controller: CiviDistManagerBundle:Check:check }

download_redir:
    path:     /latest
    defaults: { _controller: CiviDistManagerBundle:Redir:append, suffix: '/' }

download:
    path:     /latest/
    defaults: { _controller: CiviDistManagerBundle:Check:downloadList }

download_file:
    path:     /latest/{file}
    defaults: { _controller: CiviDistManagerBundle:Check:download }

browse_branch_redir:
    path:     /latest/branch/{branch}
    defaults: { _controller: CiviDistManagerBundle:Redir:append, suffix: '/' }

browse_branch:
    path:     /latest/branch/{branch}/
    defaults: { _controller: CiviDistManagerBundle:AutoBuild:browse }

browse_branch_build_redir:
    path:     /latest/branch/{branch}/{ts}
    defaults: { _controller: CiviDistManagerBundle:Redir:append, suffix: '/' }

browse_branch_build:
    path:     /latest/branch/{branch}/{ts}/
    defaults: { _controller: CiviDistManagerBundle:AutoBuild:view }

download_branch_file:
    path:     /latest/branch/{branch}/{ts}/{basename}
    defaults: { _controller: CiviDistManagerBundle:AutoBuild:download }

inspect_branch_build:
    path:     /latest/branch/{branch}/{ts}/{basename}/inspect
    defaults: { _controller: CiviDistManagerBundle:Redir:parent, levels: 2 }

release_list:
    path:     /release/
    defaults: { _controller: release_controller:listAction }

release_version:
    path:     /release/{version}
    defaults: { _controller: release_controller:viewAction }

esr_redir:
    path:     /esr
    defaults: { _controller: CiviDistManagerBundle:Redir:append, suffix: '/' }

esr_base:
    path:     /esr/
    defaults: { _controller: esr_controller:browseAction, path: null }

esr_path:
    path:     /esr/{path}
    defaults: { _controller: esr_controller:browseAction }
    requirements:
      path: .+

joomla_xml:
    path: /joomla.xml
    defaults: { _controller: CiviDistManagerBundle:Joomla:index, suffix: "-joomla.zip" }

joomla5_xml:
    path: /joomla5.xml
    defaults: { _controller: CiviDistManagerBundle:Joomla:index, suffix: "-joomla5.zip" }
