
check:
    path:     /check
    defaults: { _controller: CiviDistManagerBundle:Check:check }

download_redir:
    path:     /latest
    defaults: { _controller: CiviDistManagerBundle:Redir:append, suffix: '/' }

download:
    path:     /latest/
    defaults: { _controller: CiviDistManagerBundle:Check:downloadList }

download_file:
    path:     /latest/{file}
    defaults: { _controller: CiviDistManagerBundle:Check:download }

inspect_file:
    path:     /latest/{file}/inspect
    defaults: { _controller: CiviDistManagerBundle:Check:inspect }

browse_branch:
    path:     /latest/branch/{branch}
    defaults: { _controller: CiviDistManagerBundle:Browse:browse }

download_branch_file:
    path:     /latest/branch/{branch}/{ts}/{basename}
    defaults: { _controller: CiviDistManagerBundle:Browse:download }

inspect_branch_build:
    path:     /latest/branch/{branch}/{ts}/{basename}/inspect
    defaults: { _controller: CiviDistManagerBundle:Browse:inspect }

about_version:
    path:     /about/{version}
    defaults: { _controller: CiviDistManagerBundle:About:view }

esr_redir:
    path:     /esr
    defaults: { _controller: CiviDistManagerBundle:Redir:append, suffix: '/' }

esr_base:
    path:     /esr/
    defaults: { _controller: esr_controller:browseAction, path: null }

esr_path:
    path:     /esr/{path}
    defaults: { _controller: esr_controller:browseAction }
    requirements:
      path: .+
