parameters:
    gcloud_cred: "%kernel.root_dir%/config/gcloud.json"
    gcloud_project: "nifty-buffer-107523"
    gcloud_build_bucket: "civicrm-build"
    gcloud_url_ttl: "+6 hour"

services:
#    civi_upgrade_manager.example:
#        class: CiviDistManagerBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  civi_upgrade_manager.dist_cache:
    class: 'Doctrine\Common\Cache\FilesystemCache'
    arguments: ['%kernel.cache_dir%/dist']

  gsu:
    class: 'CiviDistManagerBundle\GStorageUrlFacade'
    arguments: ['@civi_upgrade_manager.dist_cache', '@gcloud_storage']

  build_repository:
    class: CiviDistManagerBundle\BuildRepository
    arguments: [ '@event_dispatcher', '@gcloud_build_bucket', '@civi_upgrade_manager.dist_cache' ]

  rev_doc_repository:
    class: CiviDistManagerBundle\RevDocRepository
    arguments: [ '@gcloud_build_bucket', '@civi_upgrade_manager.dist_cache', '@build_repository', '%gcloud_url_ttl%' ]

  gcloud_storage:
    class: Google\Cloud\Storage\StorageClient
    factory: ['CiviDistManagerBundle\GCloudFactory', createStorageClient]
    arguments: ['%gcloud_cred%', '%gcloud_project%']

  gcloud_build_bucket:
    class: Google\Cloud\Storage\Bucket
    factory: ['CiviDistManagerBundle\GCloudFactory', createBucket]
    arguments: ['@gcloud_storage', '%gcloud_build_bucket%']

  public_branch_filter:
    class: 'CiviDistManagerBundle\PublicBranchFilter'
    arguments: ['@civi_upgrade_manager.dist_cache']
    tags:
     -
       name: 'kernel.event_subscriber'
