parameters:
    gcloud_cred: "%kernel.root_dir%/config/gcloud.json"
    gcloud_project: "nifty-buffer-107523"
    gcloud_bucket: "civicrm-build"

services:
#    civi_upgrade_manager.example:
#        class: CiviDistManagerBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  civi_upgrade_manager.dist_cache:
    class: 'Doctrine\Common\Cache\FilesystemCache'
    arguments: ['%kernel.cache_dir%/dist']

  build_repository:
    class: CiviDistManagerBundle\BuildRepository
    arguments: [ '@gcloud_bucket', '@civi_upgrade_manager.dist_cache' ]

  gcloud_storage:
    class: Google\Cloud\Storage\StorageClient
    factory: ['CiviDistManagerBundle\GCloudFactory', createStorageClient]
    arguments: ['%gcloud_cred%', '%gcloud_project%']

  gcloud_bucket:
    class: Google\Cloud\Storage\Bucket
    factory: ['CiviDistManagerBundle\GCloudFactory', createBucket]
    arguments: ['@gcloud_storage', '%gcloud_bucket%']
